apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T02:21:13Z"
  name: carts-canary
  resourceVersion: "1141827"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 118fed5d-1c86-11ea-b756-42010a98001b
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
